name: target-determination

on:
  workflow_call:

jobs:
  target-determination:
    # Don't run on forked repos
    if: github.repository_owner == 'pytorch'
    runs-on: linux.2xlarge
    steps:
      # [pytorch repo ref]
      # Use a pytorch/pytorch reference instead of a reference to the local
      # checkout because when we run this action we don't *have* a local
      # checkout. In other cases you should prefer a local checkout.
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main

      - name: Setup Linux
        uses: ./.github/actions/setup-linux

      - name: Download pytest cache
        uses: ./.github/actions/pytest-cache-download
        continue-on-error: true
        with:
          cache_dir: .pytest_cache
          job_identifier: ${{ github.workflow }}

      - name: Do TD
        id: td
        run: |
          python3 tools/testing/do_target_determination_for_s3.py

      - name: Upload TD results to s3
        uses: seemethere/upload-artifact-s3@v5
        if: steps.td.outcome != 'skipped'
        with:
          name: td_results
          retention-days: 14
          if-no-files-found: error
          path: td_results.json

      - name: Store TD results on GHA
        uses: actions/upload-artifact@v3
        if: steps.td.outcome != 'skipped'
        with:
          name: td_results.json
          retention-days: 14
          if-no-files-found: error
          path: td_results.json
